configured_endpoints: 4
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/greenflash%2Fgreenflash-public-api-4c0b5a58aca4430e347dd9deabe8bbdcb463bb63b9a5adbc1ae647dc8b74dad6.yml
openapi_spec_hash: bd17acd36822bb072413809baf136465
config_hash: 2b7ac5d60c7fc52be0e65679c7cf8dbf
