configured_endpoints: 34
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/greenflash/greenflash-public-api-a12ee2df584980d6e51dff79d41acaf8ad0a7cb91fe7ea8be33c03febc4bca42.yml
openapi_spec_hash: 3ced06bebddb9e30c0e360ce68fada3a
config_hash: 96c913fa5e6baa275c61323fa03f9d2c
